[package]
name             = "kaname-oobv"
version.workspace     = true
edition.workspace     = true
rust-version.workspace = true
license.workspace     = true
publish             = false

[dependencies]
serde      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }
kaname-crypto = { path = "../kaname-crypto" }
kaname-memory-guard = { path = "../kaname-memory-guard" }
rand       = { workspace = true }
zeroize    = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
