[package]
name             = "kaname-mls"
version.workspace     = true
edition.workspace     = true
rust-version.workspace = true

[dependencies]
serde      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }
tokio      = { workspace = true }
tracing    = { workspace = true }
kaname-error = { path = "../kaname-error" }
sha2         = { workspace = true }
rand         = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
proptest = { workspace = true }
